Name:           ros-indigo-iai-common-msgs
Version:        0.0.6
Release:        0%{?dist}
Summary:        ROS iai_common_msgs package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-attache-msgs
Requires:       ros-indigo-data-vis-msgs
Requires:       ros-indigo-designator-integration-msgs
Requires:       ros-indigo-dna-extraction-msgs
Requires:       ros-indigo-grasp-stability-msgs
Requires:       ros-indigo-iai-content-msgs
Requires:       ros-indigo-iai-control-msgs
Requires:       ros-indigo-iai-kinematics-msgs
Requires:       ros-indigo-iai-robosherlock-actions
Requires:       ros-indigo-iai-urdf-msgs
Requires:       ros-indigo-iai-wsg-50-msgs
Requires:       ros-indigo-json-prolog-msgs
Requires:       ros-indigo-mln-robosherlock-msgs
Requires:       ros-indigo-person-msgs
Requires:       ros-indigo-planning-msgs
Requires:       ros-indigo-saphari-msgs
Requires:       ros-indigo-scanning-table-msgs
Requires:       ros-indigo-sherlock-sim-msgs
BuildRequires:  ros-indigo-catkin

%description
Message definitions created and used by the Institute for Artificial
Intelligence research group at the University of Bremen

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Apr 21 2016 AI Robotics <ai-robotics@cs.uni-bremen.de> - 0.0.6-0
- Autogenerated by Bloom

* Tue Dec 15 2015 AI Robotics <ai-robotics@cs.uni-bremen.de> - 0.0.5-3
- Autogenerated by Bloom

* Tue Dec 15 2015 AI Robotics <ai-robotics@cs.uni-bremen.de> - 0.0.5-2
- Autogenerated by Bloom

* Wed Nov 25 2015 AI Robotics <ai-robotics@cs.uni-bremen.de> - 0.0.5-1
- Autogenerated by Bloom

* Fri Apr 24 2015 AI Robotics <ai-robotics@cs.uni-bremen.de> - 0.0.5-0
- Autogenerated by Bloom

* Thu Mar 19 2015 AI Robotics <ai-robotics@cs.uni-bremen.de> - 0.0.4-0
- Autogenerated by Bloom

* Wed Dec 10 2014 AI Robotics <ai-robotics@cs.uni-bremen.de> - 0.0.3-1
- Autogenerated by Bloom

* Tue Oct 14 2014 AI Robotics <ai-robotics@cs.uni-bremen.de> - 0.0.3-0
- Autogenerated by Bloom

